# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'
    
    - name: Get Dependencies
      run: go get github.com/CycloneDX/cyclonedx-go
      
    - name: Build
      run: go build ./cmd/dotnetbomcleaner/

    - name: Upload executable
      uses: actions/upload-artifact@v4
      with:
        name: dotnetbomcleaner
        path: ./dotnetbomcleaner
        compression-level: 0
